version: '3.2'

services:
  neneka:
    image: neneka
    build: .
    container_name: neneka
    volumes:
      - ./:/app
    command: gunicorn neneka.app:app -b :8080 --worker-class aiohttp.GunicornWebWorker --reload --access-logfile -
    ports:
      - "8080:8080"
    depends_on:
      - db_neneka
  db_neneka:
    image: postgres
    restart: always
    container_name: db_neneka
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
